from __future__ import annotations

from types import ModuleType
from typing import Any, Iterator, Protocol

import numpy as np
import array_api_compat


class Array(Protocol):
    """Protocol for Python Array API-compliant arrays.

    Any array satisfying this protocol (numpy ndarray, CuPy ndarray,
    PyTorch Tensor, ...) can be used wherever :class:`Array` is expected.
    The declared operations correspond to the Python Array API standard
    (https://data-apis.org/array-api/latest/API_specification/array_object.html).
    """

    # ------------------------------------------------------------------
    # Attributes
    # ------------------------------------------------------------------

    @property
    def dtype(self) -> Any: ...
    @property
    def device(self) -> Any: ...
    @property
    def ndim(self) -> int: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def size(self) -> int: ...
    @property
    def T(self) -> Any: ...
    @property
    def mT(self) -> Any: ...

    # ------------------------------------------------------------------
    # Conversion
    # ------------------------------------------------------------------

    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __complex__(self) -> complex: ...
    def __index__(self) -> int: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Any]: ...

    # ------------------------------------------------------------------
    # Indexing
    # ------------------------------------------------------------------

    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...

    # ------------------------------------------------------------------
    # Arithmetic operators
    # ------------------------------------------------------------------

    def __pos__(self) -> Any: ...
    def __neg__(self) -> Any: ...
    def __add__(self, other: Any) -> Any: ...
    def __radd__(self, other: Any) -> Any: ...
    def __iadd__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __rsub__(self, other: Any) -> Any: ...
    def __isub__(self, other: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> Any: ...
    def __imul__(self, other: Any) -> Any: ...
    def __truediv__(self, other: Any) -> Any: ...
    def __rtruediv__(self, other: Any) -> Any: ...
    def __itruediv__(self, other: Any) -> Any: ...
    def __floordiv__(self, other: Any) -> Any: ...
    def __rfloordiv__(self, other: Any) -> Any: ...
    def __ifloordiv__(self, other: Any) -> Any: ...
    def __mod__(self, other: Any) -> Any: ...
    def __rmod__(self, other: Any) -> Any: ...
    def __imod__(self, other: Any) -> Any: ...
    def __pow__(self, other: Any) -> Any: ...
    def __rpow__(self, other: Any) -> Any: ...
    def __ipow__(self, other: Any) -> Any: ...

    # ------------------------------------------------------------------
    # Matrix multiplication
    # ------------------------------------------------------------------

    def __matmul__(self, other: Any) -> Any: ...
    def __rmatmul__(self, other: Any) -> Any: ...
    def __imatmul__(self, other: Any) -> Any: ...

    # ------------------------------------------------------------------
    # Bitwise operators
    # ------------------------------------------------------------------

    def __invert__(self) -> Any: ...
    def __and__(self, other: Any) -> Any: ...
    def __rand__(self, other: Any) -> Any: ...
    def __iand__(self, other: Any) -> Any: ...
    def __or__(self, other: Any) -> Any: ...
    def __ror__(self, other: Any) -> Any: ...
    def __ior__(self, other: Any) -> Any: ...
    def __xor__(self, other: Any) -> Any: ...
    def __rxor__(self, other: Any) -> Any: ...
    def __ixor__(self, other: Any) -> Any: ...
    def __lshift__(self, other: Any) -> Any: ...
    def __rlshift__(self, other: Any) -> Any: ...
    def __ilshift__(self, other: Any) -> Any: ...
    def __rshift__(self, other: Any) -> Any: ...
    def __rrshift__(self, other: Any) -> Any: ...
    def __irshift__(self, other: Any) -> Any: ...

    # ------------------------------------------------------------------
    # Comparison operators
    # ------------------------------------------------------------------

    def __lt__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...  # type: ignore[override]
    def __ne__(self, other: Any) -> Any: ...  # type: ignore[override]

    # ------------------------------------------------------------------
    # Interoperability
    # ------------------------------------------------------------------

    def __array_namespace__(self, *, api_version: str | None = None) -> Any: ...
    def __dlpack__(self, *, stream: Any = None) -> Any: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...
    def to_device(self, device: Any, /, *, stream: Any = None) -> Any: ...


def to_numpy_array(x: Array) -> np.ndarray:
    if array_api_compat.is_cupy_array(x):
        cp = array_api_compat.get_namespace(x)

        return cp.asnumpy(x)
    elif array_api_compat.is_torch_array(x):
        return (
            x.detach().numpy() if x.device.type == "cpu" else x.detach().cpu().numpy()
        )
    else:
        return np.asarray(x)


def empty_cuda_cache(xp: ModuleType) -> None:
    """Empty cached CUDA memory for supported backends.

    For unsupported or non-CUDA namespaces (e.g. NumPy), do nothing.
    """
    if array_api_compat.is_cupy_namespace(xp):
        xp.get_default_memory_pool().free_all_blocks()
        xp.get_default_pinned_memory_pool().free_all_blocks()
    elif array_api_compat.is_torch_namespace(xp):
        torch_mod = getattr(xp, "torch", xp)
        if torch_mod.cuda.is_available():
            torch_mod.cuda.empty_cache()


def count_event_multiplicity(events: Array) -> Array:
    """Count the multiplicity of each event row."""
    xp = array_api_compat.get_namespace(events)

    if events.ndim != 2:
        raise ValueError("events must be a 2D array")

    if array_api_compat.is_torch_namespace(xp):
        return _count_event_multiplicity_torch(events, xp)
    elif array_api_compat.is_cupy_namespace(xp):
        return _count_event_multiplicity_cupy(events, xp)
    else:
        return _count_event_multiplicity_numpy_fallback(events, xp)


def _count_event_multiplicity_torch(events: Array, xp) -> Array:
    torch_mod = _native_torch_module(xp)
    _, inverse, counts = torch_mod.unique(
        events,
        dim=0,
        return_inverse=True,
        return_counts=True,
    )
    return counts[inverse].reshape(-1)


def _count_event_multiplicity_cupy(events: Array, xp) -> Array:
    cupy_mod = xp
    _, inverse, counts = cupy_mod.unique(
        events,
        axis=0,
        return_inverse=True,
        return_counts=True,
    )
    return counts[inverse].reshape(-1)


def _count_event_multiplicity_numpy_fallback(events: Array, xp) -> Array:
    x_np = to_numpy_array(events)
    _, inverse, counts = np.unique(
        x_np,
        axis=0,
        return_inverse=True,
        return_counts=True,
    )
    return xp.asarray(counts[inverse].reshape(-1))


def _native_torch_module(xp):
    return xp if xp.__name__ == "torch" else xp.torch
