"""
Axial sinogram plane symmetries for a PET scanner with cylindrical symmetry.

For a cylindrically-symmetric imaged object (e.g. a uniform cylinder or a
rotating line source) the expected counts on a sinogram plane (r1, r2) depend
only on the axial ring-pair geometry — not on the azimuthal angle.  Within
the axial direction, three independent symmetries reduce the number of
geometrically distinct planes that need to be measured or calculated:

1. **Axial block shift**: shifting both ring indices by one full block width
   maps every crystal to the crystal at the same position in the adjacent block.
   Detector efficiency and geometry are therefore preserved.

2. **Scanner midplane reflection**: reflecting the scanner about its axial
   centre maps ring r to ring N−1−r.  For a z-symmetric imaged object this
   maps each plane (r1, r2) to an equivalent plane.

3. **Endpoint swap**: exchanging (r1, r2) with (r2, r1) describes the same
   physical LOR traversed in the opposite direction; expected counts are equal.

Edge correction (``n_edge > 0``): the outermost ``n_edge`` rings of the first
and last detector block are missing a neighbouring block on one side.  Their
crystal sensitivity differs from the same intra-block position in interior
blocks, so the axial block-shift equivalence is restricted to ring pairs that
stay within the same interior / edge category after the shift.
"""

from __future__ import annotations


def is_interior_ring(ring: int, num_rings: int, n_edge: int) -> bool:
    """Return True iff *ring* is not affected by edge effects.

    Rings 0 … n_edge−1 and N−n_edge … N−1 are *edge rings* — they sit at the
    outer face of the first / last detector block and have no neighbouring
    block on one side.  All others are *interior* rings.  ``n_edge=0`` treats
    every ring as interior (no edge correction).
    """
    if n_edge <= 0:
        return True
    return n_edge <= ring < num_rings - n_edge


def axially_mirrored_plane(r1: int, r2: int, num_rings: int) -> tuple[int, int]:
    """Return the plane obtained by reflecting the scanner about its axial midplane.

    Reflection maps ring r → N−1−r, so plane (r1, r2) becomes
    (N−1−r2, N−1−r1).  The endpoint order is reversed so that the mirrored
    plane has the same sign of ring difference as the original.
    """
    return num_rings - 1 - r2, num_rings - 1 - r1


def swapped_plane(r1: int, r2: int) -> tuple[int, int]:
    """Return (r2, r1) — the same LOR traversed in the opposite axial direction."""
    return r2, r1


def axial_block_shifted_planes(
    r1: int,
    r2: int,
    block_size: int,
    num_rings: int,
    n_edge: int = 0,
) -> list[tuple[int, int]]:
    """All planes obtained by shifting both ring indices by a multiple of *block_size*.

    When ``n_edge > 0`` only shifts are returned in which both endpoints remain
    in the same interior / edge category as the originals — preventing
    edge-of-scanner rings from being treated as equivalent to interior rings.
    """
    num_blocks = num_rings // block_size
    shifted = [
        (r1 + k * block_size, r2 + k * block_size)
        for k in range(-num_blocks, num_blocks + 1)
        if 0 <= r1 + k * block_size < num_rings
        and 0 <= r2 + k * block_size < num_rings
    ]
    if n_edge <= 0:
        return shifted
    cat_r1 = is_interior_ring(r1, num_rings, n_edge)
    cat_r2 = is_interior_ring(r2, num_rings, n_edge)
    return [
        (ra, rb)
        for ra, rb in shifted
        if is_interior_ring(ra, num_rings, n_edge) == cat_r1
        and is_interior_ring(rb, num_rings, n_edge) == cat_r2
    ]


def plane_orbit(
    r1: int,
    r2: int,
    block_size: int,
    num_rings: int,
    n_edge: int = 0,
) -> list[tuple[int, int]]:
    """Return all sinogram planes equivalent to (r1, r2) under the three axial symmetries.

    The orbit is generated by applying — and composing — the axial block shift,
    the scanner midplane reflection, and the endpoint swap.
    """
    seeds = [
        (r1, r2),
        axially_mirrored_plane(r1, r2, num_rings),
        swapped_plane(r1, r2),
        swapped_plane(*axially_mirrored_plane(r1, r2, num_rings)),
    ]
    orbit: set[tuple[int, int]] = set()
    for seed in seeds:
        for plane in axial_block_shifted_planes(*seed, block_size, num_rings, n_edge):
            orbit.add(plane)
    return sorted(orbit)


def compute_sinogram_plane_symmetries(
    block_size: int,
    num_blocks: int,
    max_ring_diff: int | None = None,
    n_edge: int = 0,
) -> tuple[dict, dict, int]:
    """Partition all span-1 sinogram planes into axial equivalence classes.

    Parameters
    ----------
    block_size : int
        Number of axial crystals per detector block.
    num_blocks : int
        Number of axial detector blocks (total rings = block_size × num_blocks).
    max_ring_diff : int or None
        Maximum |r1 − r2| included in the sinogram.  ``None`` includes all planes.
    n_edge : int
        Number of edge rings at each scanner end with different sensitivity
        due to missing neighbouring blocks.  ``0`` disables edge correction.

    Returns
    -------
    plane_to_class : dict[(int, int), int]
        Maps every valid sinogram plane to its equivalence-class index.
    class_to_planes : dict[int, list[(int, int)]]
        Reverse lookup: class index → sorted list of member planes.
    num_classes : int
        Total number of distinct equivalence classes.
    """
    num_rings = block_size * num_blocks
    if max_ring_diff is None:
        max_ring_diff = num_rings - 1

    remaining: set[tuple[int, int]] = {
        (r1, r2)
        for r1 in range(num_rings)
        for r2 in range(num_rings)
        if abs(r1 - r2) <= max_ring_diff
    }
    plane_to_class: dict = {}
    class_to_planes: dict = {}
    class_idx = 0
    while remaining:
        seed = min(remaining)
        members = sorted(
            p
            for p in plane_orbit(*seed, block_size, num_rings, n_edge)
            if abs(p[0] - p[1]) <= max_ring_diff
        )
        class_to_planes[class_idx] = members
        for plane in members:
            plane_to_class[plane] = class_idx
            remaining.discard(plane)
        class_idx += 1
    return plane_to_class, class_to_planes, class_idx
