name: readthedocs-pp
channels:
  - conda-forge
dependencies:
  - pip
  - parallelproj-core
  - libparallelproj>=2.0
  - sphinx
  - sphinx-gallery
  - sphinx-design
  - furo
  - sphinxcontrib-bibtex
  - matplotlib
  - array-api-compat
  - pytorch
  - scipy
