name: readthedocs-pp
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - parallelproj-core>=2.0.5
  - sphinx
  - sphinx-gallery
  - sphinx-design
  - furo
  - sphinxcontrib-bibtex
  - matplotlib
  - array-api-compat
  - pytorch
  - scipy
